Feature/profile picture
smartive-education/design-system-component-library-z-index pull request #25
Opened 2022-12-21 16:43 UTC by ricardovoegeli

2022-12-22 16:44 UTC, tthttl requested changes

2022-12-22 16:44 UTC, tthttl commented on src/Components/ProfilePicture/ProfilePicture.tsx
> +      className={`cursor-pointer rounded-full object-cover overflow-hidden ${getClasses(size).div} ${!getImage(src, size) && 'bg-pink-300' || ''}`}>
hmm ich finde es ein bisschen unlesbar, vielleicht so?
 getImage(src, size) ? 'bg-pink-300' : ''

2022-12-22 16:44 UTC, tthttl commented on src/Components/ProfilePicture/ProfilePicture.tsx
> +    div: '',
ich denke "outline outline-8 outline-slate-100" soll noch in div, und image wird nirgendwo gebraucht.

2022-12-22 16:44 UTC, tthttl commented on package.json
> +    "typescript": "4.9.4"
wieso hast du das angepasst?

2022-12-22 19:16 UTC, ricardovoegeli commented on src/Components/ProfilePicture/ProfilePicture.tsx
> +      className={`cursor-pointer rounded-full object-cover overflow-hidden ${getClasses(size).div} ${!getImage(src, size) && 'bg-pink-300' || ''}`}>
wegen farben habe ein test gemacht dann vergessen Danke. Wegen unlesbar finde ich gleich, haben wir gesagt nicht auf so kleine details anschauen aber wie du willst

2022-12-22 19:16 UTC, ricardovoegeli commented on package.json
> +    "typescript": "4.9.4"
gefixt, musst alles wieder installieren

2022-12-22 19:18 UTC, ricardovoegeli commented on src/Components/ProfilePicture/ProfilePicture.tsx
> +    div: '',
bist du sicher? so ist für mich perfekt

2022-12-23 10:03 UTC, tthttl commented on src/Components/ProfilePicture/ProfilePicture.tsx
> +    div: '',
ja ohne das hat es kein outline, oder?

2022-12-23 10:04 UTC, merged