Feature/UserWidget
smartive-education/design-system-component-library-z-index pull request #28
Opened 2022-12-26 16:20 UTC by ricardovoegeli

2022-12-27 12:58 UTC, tthttl requested changes

2022-12-27 12:58 UTC, tthttl commented on src/Components/ButtonGroup/ButtonGroup.tsx
> +      <Button type="button" id={LId} color={LColor} size={LSize} label={LLabel} onClick={LOnClick} icon={LIcon} />
ich denke dein prettier im vs code ist noch nicht richtig. in prettierrc steht single quotes

2022-12-27 12:58 UTC, tthttl commented on src/Components/ProfilePicture/ProfilePicture.tsx
> +  onEdit?: () => void;
das habe ich auch in meinem PR (welche noch offen ist) geändert => ich würde grundsätzlich zuerst das mergen, sonst wirst möglicherweise merge conflicts haben.

2022-12-27 12:58 UTC, tthttl commented on src/Components/ProfilePicture/ProfilePicture.tsx
> +      return '/assets/images/profile/no.image.png';
nochmal, bitte merge zuerst mein feature/misc branch => path muss ohne / eingegeben werden, sonst funktioniert die deployte version auf github pages nicht

2022-12-27 12:58 UTC, tthttl commented on src/Components/UserWidget copy/UserWidgetRow.tsx
> +      <div className="p-2 min-w-[216px] w-[216px]">
pixel genau einheiten sind nicht responsive, bitte verwende rem, wenn du etwas fixes möchtest. ausserdem, hast du gecheckt ob es auf mobile auch ok aussieht?

2022-12-28 10:29 UTC, tthttl commented on src/Components/ProfilePicture/ProfilePicture.tsx
> +      return '/assets/images/profile/no.image.png';
heey, wieso hast du diesen Kommentar resolved markiert?

2022-12-28 10:33 UTC, ricardovoegeli commented on src/Components/ProfilePicture/ProfilePicture.tsx
> +      return '/assets/images/profile/no.image.png';
eh? komisch! ich habe geändert und ist wieder mit /, fixe es gerade

2022-12-28 10:33 UTC, tthttl commented on src/Components/UserWidget copy/UserWidgetRow.tsx
> +      <div className="p-2 min-w-[216px] w-[216px]">
px ist gefixt, aber der zweite Teil/Frage bleibt immer noch offen: was ist mit mobile? ich denke nicht dass wir da Platz haben für 3 columns nebeneinander. kannst du bitte hier viellecht ein responsive grid verwenden, welche je nach grösse entweder 3 oder 2 columns anzeigt? wenn du das machst, dann brauchst du nicht mal die width zu fixen. beispiel wäre die Header component.

2022-12-28 10:36 UTC, tthttl commented on src/Components/UserWidget copy/UserWidgetRow.tsx
> +        <UserWidget src="/assets/images/profile/r.vogt.jpg" name="Damian Caduff" size="small" username="damiancaduff" />
src sollte wahrscheinlich ein prop sein hier, es ist nicht immer Robert und Damian den wir anzeigen möchten :)

2022-12-28 10:37 UTC, ricardovoegeli commented on src/Components/ProfilePicture/ProfilePicture.tsx
> +      return '/assets/images/profile/no.image.png';
aha diese änderung brauche ich nicht mehr, wurde von dein merge gefixt, schau in Files Changed, ist nicht mehr da

2022-12-28 10:38 UTC, tthttl commented on src/Components/UserWidget copy/UserWidgetRow.tsx
> +import React, { FC } from 'react';
Der file Name ist falsch => UserWidget copy

2022-12-28 10:40 UTC, ricardovoegeli commented on src/Components/UserWidget copy/UserWidgetRow.tsx
> +import React, { FC } from 'react';
gefixt

2022-12-28 10:40 UTC, ricardovoegeli commented on src/Components/UserWidget copy/UserWidgetRow.tsx
> +        <UserWidget src="/assets/images/profile/r.vogt.jpg" name="Damian Caduff" size="small" username="damiancaduff" />
gefixt

2022-12-28 10:42 UTC, tthttl commented on src/Components/UserWidget/UserWidget.tsx
> +        <ProfilePicture name="rvogt" size="medium" src="/assets/images/profile/r.vogt.jpg" />
src prop weitergeben, nicht robert hardcodieren :)

2022-12-28 10:45 UTC, tthttl commented on src/Components/UserWidget/UserWidget.stories.tsx
> +  src: '/assets/images/profile/r.vogt.jpg',
path

2022-12-28 10:51 UTC, tthttl commented on src/Components/UserWidget copy/UserWidgetRow.tsx
> +      <div className="p-2 min-w-[216px] w-[216px]">
vielleicht was noch besser wäre, wenn es nicht ein userwidget ROW wäre sondern ein GRID => es könnte durch all die input props iterieren (map()) ünd für jede Person ein Widget rendern in einem grid mit entweder 2 oder 3 element in einem ROW.

2022-12-28 15:18 UTC, tthttl approved these changes

2022-12-30 17:30 UTC, merged