profile card edit added
smartive-education/design-system-component-library-z-index pull request #33
Opened 2023-01-05 18:22 UTC by ricardovoegeli

2023-01-07 10:14 UTC, tthttl requested changes

2023-01-07 10:14 UTC, tthttl commented on .eslintrc.json
> +  "ignorePatterns": ["**/*.stories.tsx", "dist/**/*", "src/**/*.spec.ts", "src/**/*.tsx", "src/**/*.ts"],
aaah, warum möchtest du eslint überall disabeln? :)

2023-01-07 10:18 UTC, ricardovoegeli commented on .eslintrc.json
> +  "ignorePatterns": ["**/*.stories.tsx", "dist/**/*", "src/**/*.spec.ts", "src/**/*.tsx", "src/**/*.ts"],
ich habe in internet mein Fehler gesucht, und in 2 Seiten ist das gesatanden, jetzt kann man builden und eslint typescript geht trotzdem, ich bin nicht ganz sicher, was meinst du?

2023-01-07 10:48 UTC, tthttl commented on .eslintrc.json
> +  "ignorePatterns": ["**/*.stories.tsx", "dist/**/*", "src/**/*.spec.ts", "src/**/*.tsx", "src/**/*.ts"],
1. eslintrc ist wo du konfigurierst welche files sollten für Fehler gecheckt werden. 
2. ignorepatterns ist ein option für dich um folders einzugeben wo du diese check ausschalten möchtest. typisch sind (wie bei uns) dist folder und test files. 
3. wenn du alle unsere files zu diesen ignore patterns hinzufügst schaltest du die check komplett aus. 

Findest du das ist die richtige Lösung um die Fehlers zu beheben?

2023-01-07 12:19 UTC, ricardovoegeli commented on .eslintrc.json
> +  "ignorePatterns": ["**/*.stories.tsx", "dist/**/*", "src/**/*.spec.ts", "src/**/*.tsx", "src/**/*.ts"],
Sicherlich nicht, dann ich komme nach Rapi am nächste Dienstag und werde dort die Dozenten fragen.

2023-01-10 17:47 UTC, tthttl approved these changes

2023-01-10 17:47 UTC, merged