feature/PostComment
smartive-education/design-system-component-library-z-index pull request #40
Opened 2023-01-15 14:21 UTC by ricardovoegeli

2023-01-15 15:08 UTC, tthttl requested changes

2023-01-15 15:08 UTC, tthttl commented on src/Components/PostComment/PostComment.tsx
> +          submitFn={() => { console.log('Upload Image') }}
es ist kein brauchbare Komponent wenn wir hier kein Zugriff zum File haben, welche hochgeladen wurde. ausserdem, kein console log im component bitte, höchstens in story.

2023-01-15 15:08 UTC, tthttl commented on src/Components/PostComment/PostComment.tsx
> +          ROnClick={ROnClick}
es muss das textarea value und das File zurückgeben, sonst ist das Komponent nicht brauchbar. ich würde hier nicht ROnClick verwenden sonder das onSubmit von dem form element => dann hast du Zugriff zum Form. Als Beispiel: Entry Form oder SettingsModal

2023-01-16 07:58 UTC, ricardovoegeli commented on src/Components/PostComment/PostComment.tsx
> +      <div className="hidden md:block">
Wieso? ist nicht nötig in React, wir benutzen kein html Post

2023-01-16 19:25 UTC, merged